# Generated by Django 2.0.2 on 2018-05-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interlock',
            fields=[
                ('mac', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('manufacturing_date', models.DateField(blank=True)),
                ('controller_serial_number', models.IntegerField(blank=True)),
                ('relay_box_serial_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterlockLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interlock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.Interlock')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_inventory_number', models.CharField(blank=True, max_length=30)),
                ('manufacturer_serial_number', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('kind_of_swipe_needed', models.CharField(choices=[('single', 'single'), ('two students', 'two students'), ('supervisor', 'supervisor')], default='single', max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('minutes_enabled', models.CharField(max_length=30)),
                ('uses_estop', models.BooleanField()),
                ('lab_containing_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('university_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind_of_person', models.CharField(choices=[('undergraduate', 'undergraduate'), ('two students', 'gradstudent'), ('ta', 'ta'), ('staff', 'staff'), ('faculty', 'faculty'), ('all access', 'all access')], default='undergraduate', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='supervisor_list',
            field=models.ManyToManyField(db_table='MachineSupervisorPersonJoinTable', related_name='supervisors', to='ui.Person'),
        ),
        migrations.AddField(
            model_name='machine',
            name='user_list',
            field=models.ManyToManyField(db_table='MachineUserPersonJoinTable', related_name='users', to='ui.Person'),
        ),
        migrations.AddField(
            model_name='interlocklookup',
            name='machine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.Machine'),
        ),
    ]
